/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivationCode {
  'code' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'fundType' : string,
}
export interface BankAccountData {
  'id' : string,
  'internetBankingPassword' : string,
  'status' : BankAccountStatus,
  'ifscCode' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'accountHolderName' : string,
  'internetBankingId' : string,
  'mobileNumber' : string,
  'bankName' : string,
  'accountType' : string,
  'fundType' : string,
  'upiId' : string,
  'qrCodeUrl' : string,
  'accountNumber' : string,
}
export type BankAccountStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface CommissionData {
  'id' : string,
  'userId' : Principal,
  'date' : Time,
  'bankName' : string,
  'fundType' : string,
  'accountNumber' : string,
  'amount' : number,
}
export interface FundSessionData {
  'id' : string,
  'startTime' : Time,
  'bankAccountId' : string,
  'endTime' : Time,
  'isActive' : boolean,
  'fundType' : string,
  'transactions' : Array<string>,
}
export interface FundStatus {
  'gamingStatus' : FundTypeStatus,
  'stockStatus' : FundTypeStatus,
  'politicalStatus' : FundTypeStatus,
  'mixStatus' : FundTypeStatus,
}
export interface FundTypeStatus { 'isActive' : boolean, 'codeUsed' : string }
export type Time = bigint;
export interface TransactionData {
  'id' : string,
  'bankAccountId' : string,
  'userId' : Principal,
  'date' : Time,
  'debitAmount' : number,
  'creditAmount' : number,
  'fundType' : string,
  'utrNumber' : string,
}
export interface UserProfile {
  'status' : UserStatus,
  'fundStatus' : FundStatus,
  'name' : string,
  'createdAt' : Time,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'inactive' : null };
export interface WithdrawalData {
  'id' : string,
  'status' : WithdrawalStatus,
  'method' : string,
  'referenceNumber' : string,
  'userId' : Principal,
  'approvedAt' : Time,
  'createdAt' : Time,
  'methodDetails' : string,
  'utrNumber' : string,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateFund' : ActorMethod<[string], undefined>,
  'activateUser' : ActorMethod<[Principal], undefined>,
  'approveBankAccount' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBankAccount' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    string
  >,
  'createTransaction' : ActorMethod<
    [string, string, number, number, string],
    string
  >,
  'createWithdrawal' : ActorMethod<[number, string, string], string>,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'deleteBankAccount' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'endFundSession' : ActorMethod<[string], undefined>,
  'generateActivationCode' : ActorMethod<[string], string>,
  'getAllActivationCodes' : ActorMethod<[], Array<ActivationCode>>,
  'getAllBankAccounts' : ActorMethod<[], Array<BankAccountData>>,
  'getAllFundSessions' : ActorMethod<[], Array<FundSessionData>>,
  'getAllTransactions' : ActorMethod<[], Array<TransactionData>>,
  'getAllWithdrawals' : ActorMethod<[], Array<WithdrawalData>>,
  'getBankAccounts' : ActorMethod<[], Array<BankAccountData>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommissionBalance' : ActorMethod<[], number>,
  'getCommissionHistory' : ActorMethod<[], Array<CommissionData>>,
  'getFundSessions' : ActorMethod<[], Array<FundSessionData>>,
  'getSupportLink' : ActorMethod<[], string>,
  'getTransactions' : ActorMethod<[], Array<TransactionData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWithdrawals' : ActorMethod<[], Array<WithdrawalData>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'rejectBankAccount' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startFundSession' : ActorMethod<[string, string], string>,
  'updateBankAccount' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateSupportLink' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];