/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ActivationCode = IDL.Record({
  'code' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'fundType' : IDL.Text,
});
export const BankAccountStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const BankAccountData = IDL.Record({
  'id' : IDL.Text,
  'internetBankingPassword' : IDL.Text,
  'status' : BankAccountStatus,
  'ifscCode' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'accountHolderName' : IDL.Text,
  'internetBankingId' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'bankName' : IDL.Text,
  'accountType' : IDL.Text,
  'fundType' : IDL.Text,
  'upiId' : IDL.Text,
  'qrCodeUrl' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const FundSessionData = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'bankAccountId' : IDL.Text,
  'endTime' : Time,
  'isActive' : IDL.Bool,
  'fundType' : IDL.Text,
  'transactions' : IDL.Vec(IDL.Text),
});
export const TransactionData = IDL.Record({
  'id' : IDL.Text,
  'bankAccountId' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : Time,
  'debitAmount' : IDL.Float64,
  'creditAmount' : IDL.Float64,
  'fundType' : IDL.Text,
  'utrNumber' : IDL.Text,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const WithdrawalData = IDL.Record({
  'id' : IDL.Text,
  'status' : WithdrawalStatus,
  'method' : IDL.Text,
  'referenceNumber' : IDL.Text,
  'userId' : IDL.Principal,
  'approvedAt' : Time,
  'createdAt' : Time,
  'methodDetails' : IDL.Text,
  'utrNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const FundTypeStatus = IDL.Record({
  'isActive' : IDL.Bool,
  'codeUsed' : IDL.Text,
});
export const FundStatus = IDL.Record({
  'gamingStatus' : FundTypeStatus,
  'stockStatus' : FundTypeStatus,
  'politicalStatus' : FundTypeStatus,
  'mixStatus' : FundTypeStatus,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'fundStatus' : FundStatus,
  'name' : IDL.Text,
  'createdAt' : Time,
  'mobile' : IDL.Text,
});
export const CommissionData = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'date' : Time,
  'bankName' : IDL.Text,
  'fundType' : IDL.Text,
  'accountNumber' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateFund' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [], []),
  'approveBankAccount' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBankAccount' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createTransaction' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createWithdrawal' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'deleteBankAccount' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'endFundSession' : IDL.Func([IDL.Text], [], []),
  'generateActivationCode' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllActivationCodes' : IDL.Func([], [IDL.Vec(ActivationCode)], ['query']),
  'getAllBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountData)], ['query']),
  'getAllFundSessions' : IDL.Func([], [IDL.Vec(FundSessionData)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(TransactionData)], ['query']),
  'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalData)], ['query']),
  'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountData)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommissionBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCommissionHistory' : IDL.Func([], [IDL.Vec(CommissionData)], ['query']),
  'getFundSessions' : IDL.Func([], [IDL.Vec(FundSessionData)], ['query']),
  'getSupportLink' : IDL.Func([], [IDL.Text], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(TransactionData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalData)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'rejectBankAccount' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startFundSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateBankAccount' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSupportLink' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ActivationCode = IDL.Record({
    'code' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'fundType' : IDL.Text,
  });
  const BankAccountStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const BankAccountData = IDL.Record({
    'id' : IDL.Text,
    'internetBankingPassword' : IDL.Text,
    'status' : BankAccountStatus,
    'ifscCode' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'accountHolderName' : IDL.Text,
    'internetBankingId' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'bankName' : IDL.Text,
    'accountType' : IDL.Text,
    'fundType' : IDL.Text,
    'upiId' : IDL.Text,
    'qrCodeUrl' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const FundSessionData = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'bankAccountId' : IDL.Text,
    'endTime' : Time,
    'isActive' : IDL.Bool,
    'fundType' : IDL.Text,
    'transactions' : IDL.Vec(IDL.Text),
  });
  const TransactionData = IDL.Record({
    'id' : IDL.Text,
    'bankAccountId' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : Time,
    'debitAmount' : IDL.Float64,
    'creditAmount' : IDL.Float64,
    'fundType' : IDL.Text,
    'utrNumber' : IDL.Text,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const WithdrawalData = IDL.Record({
    'id' : IDL.Text,
    'status' : WithdrawalStatus,
    'method' : IDL.Text,
    'referenceNumber' : IDL.Text,
    'userId' : IDL.Principal,
    'approvedAt' : Time,
    'createdAt' : Time,
    'methodDetails' : IDL.Text,
    'utrNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const FundTypeStatus = IDL.Record({
    'isActive' : IDL.Bool,
    'codeUsed' : IDL.Text,
  });
  const FundStatus = IDL.Record({
    'gamingStatus' : FundTypeStatus,
    'stockStatus' : FundTypeStatus,
    'politicalStatus' : FundTypeStatus,
    'mixStatus' : FundTypeStatus,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'fundStatus' : FundStatus,
    'name' : IDL.Text,
    'createdAt' : Time,
    'mobile' : IDL.Text,
  });
  const CommissionData = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'date' : Time,
    'bankName' : IDL.Text,
    'fundType' : IDL.Text,
    'accountNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateFund' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [], []),
    'approveBankAccount' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBankAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createTransaction' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createWithdrawal' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'deleteBankAccount' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'endFundSession' : IDL.Func([IDL.Text], [], []),
    'generateActivationCode' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllActivationCodes' : IDL.Func(
        [],
        [IDL.Vec(ActivationCode)],
        ['query'],
      ),
    'getAllBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountData)], ['query']),
    'getAllFundSessions' : IDL.Func([], [IDL.Vec(FundSessionData)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(TransactionData)], ['query']),
    'getAllWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalData)], ['query']),
    'getBankAccounts' : IDL.Func([], [IDL.Vec(BankAccountData)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommissionBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCommissionHistory' : IDL.Func([], [IDL.Vec(CommissionData)], ['query']),
    'getFundSessions' : IDL.Func([], [IDL.Vec(FundSessionData)], ['query']),
    'getSupportLink' : IDL.Func([], [IDL.Text], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(TransactionData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalData)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'rejectBankAccount' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startFundSession' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateBankAccount' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSupportLink' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };