/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    status: UserStatus;
    fundStatus: FundStatus;
    name: string;
    createdAt: Time;
    mobile: string;
}
export interface WithdrawalData {
    id: string;
    status: WithdrawalStatus;
    method: string;
    referenceNumber: string;
    userId: Principal;
    approvedAt: Time;
    createdAt: Time;
    methodDetails: string;
    utrNumber: string;
    amount: number;
}
export type Time = bigint;
export interface CommissionData {
    id: string;
    userId: Principal;
    date: Time;
    bankName: string;
    fundType: string;
    accountNumber: string;
    amount: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FundTypeStatus {
    isActive: boolean;
    codeUsed: string;
}
export interface FundSessionData {
    id: string;
    startTime: Time;
    bankAccountId: string;
    endTime: Time;
    isActive: boolean;
    fundType: string;
    transactions: Array<string>;
}
export interface FundStatus {
    gamingStatus: FundTypeStatus;
    stockStatus: FundTypeStatus;
    politicalStatus: FundTypeStatus;
    mixStatus: FundTypeStatus;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ActivationCode {
    code: string;
    createdAt: Time;
    isActive: boolean;
    fundType: string;
}
export interface BankAccountData {
    id: string;
    internetBankingPassword: string;
    status: BankAccountStatus;
    ifscCode: string;
    userId: Principal;
    createdAt: Time;
    accountHolderName: string;
    internetBankingId: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    fundType: string;
    upiId: string;
    qrCodeUrl: string;
    accountNumber: string;
}
export interface TransactionData {
    id: string;
    bankAccountId: string;
    userId: Principal;
    date: Time;
    debitAmount: number;
    creditAmount: number;
    fundType: string;
    utrNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum BankAccountStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    inactive = "inactive"
}
export enum WithdrawalStatus {
    pending = "pending",
    approved = "approved"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateFund(code: string): Promise<void>;
    activateUser(user: Principal): Promise<void>;
    approveBankAccount(id: string): Promise<void>;
    approveWithdrawal(id: string, utrNumber: string, referenceNumber: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBankAccount(accountType: string, bankName: string, accountHolderName: string, accountNumber: string, ifscCode: string, mobileNumber: string, internetBankingId: string, internetBankingPassword: string, upiId: string, qrCodeUrl: string, fundType: string): Promise<string>;
    createTransaction(bankAccountId: string, utrNumber: string, creditAmount: number, debitAmount: number, fundType: string): Promise<string>;
    createWithdrawal(amount: number, method: string, methodDetails: string): Promise<string>;
    deactivateUser(user: Principal): Promise<void>;
    deleteBankAccount(id: string): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    endFundSession(sessionId: string): Promise<void>;
    generateActivationCode(fundType: string): Promise<string>;
    getAllActivationCodes(): Promise<Array<ActivationCode>>;
    getAllBankAccounts(): Promise<Array<BankAccountData>>;
    getAllFundSessions(): Promise<Array<FundSessionData>>;
    getAllTransactions(): Promise<Array<TransactionData>>;
    getAllWithdrawals(): Promise<Array<WithdrawalData>>;
    getBankAccounts(): Promise<Array<BankAccountData>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommissionBalance(): Promise<number>;
    getCommissionHistory(): Promise<Array<CommissionData>>;
    getFundSessions(): Promise<Array<FundSessionData>>;
    getSupportLink(): Promise<string>;
    getTransactions(): Promise<Array<TransactionData>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWithdrawals(): Promise<Array<WithdrawalData>>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    rejectBankAccount(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    startFundSession(bankAccountId: string, fundType: string): Promise<string>;
    updateBankAccount(id: string, accountType: string, bankName: string, accountHolderName: string, accountNumber: string, ifscCode: string, mobileNumber: string, internetBankingId: string, internetBankingPassword: string, upiId: string, qrCodeUrl: string, fundType: string): Promise<void>;
    updateSupportLink(newLink: string): Promise<void>;
}
import type { BankAccountData as _BankAccountData, BankAccountStatus as _BankAccountStatus, FundStatus as _FundStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserStatus as _UserStatus, WithdrawalData as _WithdrawalData, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateFund(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateFund(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateFund(arg0);
            return result;
        }
    }
    async activateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return result;
        }
    }
    async approveBankAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBankAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBankAccount(arg0);
            return result;
        }
    }
    async approveWithdrawal(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBankAccount(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBankAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBankAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async createTransaction(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createWithdrawal(arg0: number, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteBankAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBankAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBankAccount(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async endFundSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endFundSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endFundSession(arg0);
            return result;
        }
    }
    async generateActivationCode(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateActivationCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateActivationCode(arg0);
            return result;
        }
    }
    async getAllActivationCodes(): Promise<Array<ActivationCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivationCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivationCodes();
            return result;
        }
    }
    async getAllBankAccounts(): Promise<Array<BankAccountData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankAccounts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankAccounts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFundSessions(): Promise<Array<FundSessionData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFundSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFundSessions();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<TransactionData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return result;
        }
    }
    async getAllWithdrawals(): Promise<Array<WithdrawalData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankAccounts(): Promise<Array<BankAccountData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankAccounts();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankAccounts();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommissionBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionBalance();
            return result;
        }
    }
    async getCommissionHistory(): Promise<Array<CommissionData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommissionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommissionHistory();
            return result;
        }
    }
    async getFundSessions(): Promise<Array<FundSessionData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFundSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFundSessions();
            return result;
        }
    }
    async getSupportLink(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportLink();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportLink();
            return result;
        }
    }
    async getTransactions(): Promise<Array<TransactionData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawals(): Promise<Array<WithdrawalData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectBankAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBankAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBankAccount(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startFundSession(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.startFundSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startFundSession(arg0, arg1);
            return result;
        }
    }
    async updateBankAccount(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string, arg11: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBankAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBankAccount(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
            return result;
        }
    }
    async updateSupportLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupportLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupportLink(arg0);
            return result;
        }
    }
}
function from_candid_BankAccountData_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankAccountData): BankAccountData {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_BankAccountStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankAccountStatus): BankAccountStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalData_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalData): WithdrawalData {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    internetBankingPassword: string;
    status: _BankAccountStatus;
    ifscCode: string;
    userId: Principal;
    createdAt: _Time;
    accountHolderName: string;
    internetBankingId: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    fundType: string;
    upiId: string;
    qrCodeUrl: string;
    accountNumber: string;
}): {
    id: string;
    internetBankingPassword: string;
    status: BankAccountStatus;
    ifscCode: string;
    userId: Principal;
    createdAt: Time;
    accountHolderName: string;
    internetBankingId: string;
    mobileNumber: string;
    bankName: string;
    accountType: string;
    fundType: string;
    upiId: string;
    qrCodeUrl: string;
    accountNumber: string;
} {
    return {
        id: value.id,
        internetBankingPassword: value.internetBankingPassword,
        status: from_candid_BankAccountStatus_n13(_uploadFile, _downloadFile, value.status),
        ifscCode: value.ifscCode,
        userId: value.userId,
        createdAt: value.createdAt,
        accountHolderName: value.accountHolderName,
        internetBankingId: value.internetBankingId,
        mobileNumber: value.mobileNumber,
        bankName: value.bankName,
        accountType: value.accountType,
        fundType: value.fundType,
        upiId: value.upiId,
        qrCodeUrl: value.qrCodeUrl,
        accountNumber: value.accountNumber
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WithdrawalStatus;
    method: string;
    referenceNumber: string;
    userId: Principal;
    approvedAt: _Time;
    createdAt: _Time;
    methodDetails: string;
    utrNumber: string;
    amount: number;
}): {
    id: string;
    status: WithdrawalStatus;
    method: string;
    referenceNumber: string;
    userId: Principal;
    approvedAt: Time;
    createdAt: Time;
    methodDetails: string;
    utrNumber: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n18(_uploadFile, _downloadFile, value.status),
        method: value.method,
        referenceNumber: value.referenceNumber,
        userId: value.userId,
        approvedAt: value.approvedAt,
        createdAt: value.createdAt,
        methodDetails: value.methodDetails,
        utrNumber: value.utrNumber,
        amount: value.amount
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _UserStatus;
    fundStatus: _FundStatus;
    name: string;
    createdAt: _Time;
    mobile: string;
}): {
    status: UserStatus;
    fundStatus: FundStatus;
    name: string;
    createdAt: Time;
    mobile: string;
} {
    return {
        status: from_candid_UserStatus_n23(_uploadFile, _downloadFile, value.status),
        fundStatus: value.fundStatus,
        name: value.name,
        createdAt: value.createdAt,
        mobile: value.mobile
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BankAccountStatus {
    return "pending" in value ? BankAccountStatus.pending : "approved" in value ? BankAccountStatus.approved : "rejected" in value ? BankAccountStatus.rejected : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "approved" in value ? WithdrawalStatus.approved : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "inactive" in value ? UserStatus.inactive : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankAccountData>): Array<BankAccountData> {
    return value.map((x)=>from_candid_BankAccountData_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalData>): Array<WithdrawalData> {
    return value.map((x)=>from_candid_WithdrawalData_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: UserStatus;
    fundStatus: FundStatus;
    name: string;
    createdAt: Time;
    mobile: string;
}): {
    status: _UserStatus;
    fundStatus: _FundStatus;
    name: string;
    createdAt: _Time;
    mobile: string;
} {
    return {
        status: to_candid_UserStatus_n31(_uploadFile, _downloadFile, value.status),
        fundStatus: value.fundStatus,
        name: value.name,
        createdAt: value.createdAt,
        mobile: value.mobile
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
